name: Mirror Repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        remote_url: 
          - 'ssh://git@gitlab.com/ItzEmoji/nvim.git'
          - 'ssh://git@codeberg.org/ItzEmoji/nvim.git'
          - 'ssh://git@gitea.com/ItzEmoji/nvim.git'

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Using v4 (latest stable)
        with:
          fetch-depth: 0

      - name: Mirror to ${{ matrix.remote_url }}
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: ${{ matrix.remote_url }}
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
